### ISSUE TITLE
prepare_datastack_main.py crashes

### ISSUE THREAD

**Issue by Calcolatore** [TUDelftGeodesy/Doris#10]
When I lunch this script, at the end of it execution, it crashes with the follow message error:
`Traceback (most recent call last):
  File "prepare_datastack_main.py", line 18, in <module>
    prepare_data_stack.prepare(args.doris_input_file)
  File "/home/giovanni/doris-work/prepare_stack/prepare_datastack.py", line 51, in prepare
    password=srtm_password, username=srtm_username)
  File "/home/giovanni/doris-work/prepare_stack/create_dem.py", line 63, in create
    latlim, lonlim = self._kml_shp_2_bb(shape_filename)
  File "/home/giovanni/doris-work/prepare_stack/create_dem.py", line 419, in _kml_shp_2_bb
    dat = shapes[0]['geometry']['coordinates']
IndexError: list index out of range
`
How I can resolve it and start the processing of my images?

**Comment by Calcolatore** [comment]
There was a problem in the shape files I was using. With a more correct one the prepare script run over.
