### ISSUE TITLE
Error in Resampling and ESD

### ISSUE THREAD

**Issue by suresh24101991** [TUDelftGeodesy/Doris#14]
Hi DORIS Users, 

When I tried to execute DORIS for Sentinel data, I am facing the following issue. 

RAW_DATA_ABSOLUTE_PATH= /home/suresh/Downloads/doris/stack/20180325/swath_3/burst_4/rsmp_orig_slave_pixel.raw
Warning 4: Unable to open rsmp_orig_slave_pixel.r00 ... skipping.

ERROR 4: MFF header file read successfully, but no bands
were successfully found and opened.
Traceback (most recent call last):
  File "/home/suresh/Downloads/Doris_master/doris_stack/functions/do_reramp_SLC.py", line 71, in <module>
    ChirpFilt = get_ramp(resFilename, resampled=1, type='chirp')
  File "/home/suresh/Downloads/Doris_master/doris_stack/functions/get_ramp.py", line 82, in get_ramp
    PixRgGrid = freadbk(Path_MFF_HDR,1, 1,int(Naz_res),int(Nrg_res))
  File "/home/suresh/Downloads/Doris_master/doris_stack/functions/get_ramp.py", line 263, in freadbk
    print 'Could not open'+Path_MFF_HDR
NameError: global name 'Path_MFF_HDR' is not defined
RAW_DATA_ABSOLUTE_PATH= /home/suresh/Downloads/doris/stack/20180325/swath_3/burst_5/rsmp_orig_slave_pixel.raw
Warning 4: Unable to open rsmp_orig_slave_pixel.r00 ... skipping.

stack folder is /home/suresh/Downloads/doris/stack
burst is swath_3_burst_5_swath_3_burst_6
ps select is 1
max baseline is 200
master date is 2018-02-17
type ESD is ps
reading metadata from /home/suresh/Downloads/doris/stack/20180325/swath_3
/home/suresh/Downloads/doris/stack/20180325/swath_3
Traceback (most recent call last):
  File "/home/suresh/Downloads/Doris_master/doris_stack/functions/ESD_ps_ds.py", line 470, in <module>
    save_overlapping(stack_folder, master_date, dates, overlap)
  File "/home/suresh/Downloads/Doris_master/doris_stack/functions/ESD_ps_ds.py", line 69, in save_overlapping
    slave_1 = freadbk(burst1 + 'slave_rsmp_reramped.raw', line_start, first_pixel_this, line_length, pixel_length , 'complex64',  this_nr_oflines, this_nr_ofpixels)
  File "/home/suresh/Downloads/Doris_master/doris_stack/functions/ESD_functions.py", line 84, in freadbk
    file_dat = np.memmap(path_file, dtype=dt, mode='r', shape=(lines, pixels))
  File "/usr/lib/python2.7/dist-packages/numpy/core/memmap.py", line 221, in __new__
    fid = open(filename, (mode == 'c' and 'r' or mode)+'b')
IOError: [Errno 2] No such file or directory: 'burst_5/slave_rsmp_reramped.raw'
Traceback (most recent call last):
  File "/home/suresh/Downloads/Doris_master/doris_stack/main_code/doris_main.py", line 28, in <module>
    doris_sentinel_1.run(args.parameterfilepath, start_date, end_date, master_date)
  File "/home/suresh/Downloads/Doris_master/doris_stack/main_code/doris_sentinel_1.py", line 122, in run
    processing.esd()
  File "/home/suresh/Downloads/Doris_master/doris_stack/main_code/single_master_stack.py", line 1288, in esd
    diff_m = np.load(os.path.join(f, esd_type + '_diff_matrix.npy'))
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: '/home/suresh/Downloads/doris/stack/esd/swath_3_burst_4_swath_3_burst_5/ps_diff_matrix.npy'

Kindly help me with the issue. 

Thank you in advance. 
Regards,
Suresh Devaraj

**Comment by xiongsiting** [comment]
I ran into the same problem. I am wondering if you have solved this problem or not?
I think there should be two files  rsmp_orig_slave_pixel.raw and  rsmp_orig_slave_line.raw produced in the "resample" step, but it did not. 

Can anyone help with this issue? Thank you.

Best regards,
Si-Ting
